
project_id = "jtwygbeceundfgnkirof"
[api]
enabled = true
[db]
enabled = true
[realtime]
enabled = true
[storage]
enabled = true
[functions]
enabled = true
[functions.fetch-job-listings]
verify_jwt = true
[functions.setup-job-cron]
verify_jwt = true
